GET http://localhost:3000/product
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDQzMjUzNDcsImV4cCI6MTYwNDMyNTQwNywiYXVkIjoidW5kZWZpbmVkIiwiaXNzIjoiZ29vZ2xlLmNvbSJ9.ThPgPeFbLpscHtW3hLkDziveK6lZFti4wJBQKAv4kAA

###login Route
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "jhondoe@gmail.com",
    "password" : "1234abcd"
}

###
POST http://localhost:3000/user/register
Content-Type: application/json

{
    "username": "john",
    "email": "jhondoe@gmail.com",
    "password" : "1234abcd"
}


###
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDQzMjUyNjAsImV4cCI6MTYzNTg4Mjg2MCwiYXVkIjoiam9obiIsImlzcyI6Imdvb2dsZS5jb20ifQ.h6QOrEBaIJSDFNmSxoetdiO4rSfxJFWVBSFB5zuRGAQ"
}

###
DELETE http://localhost:3000/auth/logout